version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew build

general:
  artifacts:
    - /Users/vitaly/AndroidStudioProjects/DivCalendar/app/build/outputs/apk/

deployment:
  beta:
    branch: master
    commands:
      - cd scripts && ./build.sh