version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  test:
    docker:
        - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name:
          command: echo $googleServicesJson | base64 --decode > "app/google-services.json"
      - run:
          name: Create DivCalendarKey.jks
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 -d > DivCalendarKey.jks
      - run:
          name: Base64 DivCalendarKey.jks
          command: base64 DivCalendarKey.jks > sd.txt
      - run:
          name: Read DivCalendarKey.jks
          command: echo "$(<sd.txt )"
      - run:
          name: Create keystore.properies
          command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' $releaseKeyAlias $releaseKeyPassword $releaseKeyStore $releaseStorePassword > keystore.properties
      - run:
          name: Run Ktlint
          command: ./gradlew ktlintReleaseCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testReleaseUnitTest

workflows:
  version: 2
  testing:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - master
                - release