version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    working_directory: ~/DivCalendar
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    branches:
      only:
        - circleci-project-setup
    steps:
      - checkout
      - run:
          name: Create DivCalendarKey.jks
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 -d > DivCalendarKey
      - run:
          name: Create keystore.properies
          command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' $releaseKeyAlias $releaseKeyPassword $releaseKeyStore $releaseStorePassword > keystore.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Ktlint
          command: ./gradlew ktlintCheck
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Unit Tests
          command: ./gradlew testReleaseUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          command: ./gradlew build