version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  test:
    docker:
        - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: Run Ktlint
          command: ./gradlew ktlintDebugCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

workflows:
  version: 2
  testing:
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci-check